### ISSUE TITLE
Translate InApp alert cancel button

### ISSUE THREAD

**Issue by SonoIo** [OneSignal/OneSignal-Cordova-SDK#14]
Hi,
I noticed that there is no way to translate the "Close" label of the UIAlertView:

https://github.com/one-signal/OneSignal-Cordova-SDK/blob/master/src/ios/OneSignal.m#L740

It would be nice if I could insert the translated text on my own with `window.plugins.OneSignal.init`

**Comment by jkasten2** [comment]
@SonoIo Thanks for pointing out this translation issue. Instead of creating a parameter it should be displayed correctly internally by the SDK code based on language set in the system settings. Pull requests are welcome. :)

If you need this right away for your app I recommend you hard a different language based on your user demographics.

Thanks.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
