### ISSUE TITLE
get additionalData if app is in background or killed

### ISSUE THREAD

**Issue by msio777** [OneSignal/OneSignal-Cordova-SDK#160]
Hi,
Is there any chance if app is in background and I receive a notification but I don't tap on it. Only way I know that there is a new message that there is a number badge on the app's icon. My question is if I open right know the app. Can I get the additionalData in some way from the notification that  I received before? Is there data saved somewhere ?

Thank you for any help 
Best Regards 
Michal

**Comment by jkasten2** [comment]
@msio777 We don't currently have a way to get all unopened notifications at this time with our SDK. Nor to we have a callback that can fire as the notification is received when the app is backgrounded or closed. However it can be done with native code, see the following thread below for more details.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/30

**Comment by msio777** [comment]
thanks a lot for your answer

**Comment by hongnk** [comment]
I second this request for enhancement to improve user experience. I do not need to wake up app when there is a notification, but only want to display some data from notification when users reopen app from home screen icon, so they know there's indeed something new, because the actual update from server takes a while to arrive. If user opens app by tapping notification today then it is already good with the notificationOpenedCallback, so please also allow Cordova app to read pending notifications at load with a similar callback.
