### ISSUE TITLE
Error compiling with Xcode since the last update

### ISSUE THREAD

**Issue by mtshare** [OneSignal/OneSignal-Cordova-SDK#189]
After installing the last update of OneSignal plugin (the one with CocoaPods) i get this error:

`ld: library not found for -lPods-APPNEME`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any suggestions?

**Comment by GuiCarneiro** [comment]
I'm having the same problem

**Comment by jkasten2** [comment]
@mtshare @GuiCarneiro Can you make sure CocoaPods is installed and updated on your system by running the following?
```
sudo gem install cocoapods
pod repo update
```

**Comment by mtshare** [comment]
I keep getting this error.

**Comment by elysiopires** [comment]
Same problem here... Have anyone success with this error?

@jkasten2 @GuiCarneiro @mtshare

**Comment by elysiopires** [comment]
Hello Guys!

I got work here... 

My aproach is:
Open the folder platform > ios on xcode (Don't open the project file)
Will appear two projects your cordova project and Pods project
Click over Pods project and go to Build Settings > Search for "**No Common Blocks**" > Then change the value to **YES**

Save and be happy... after a week the problem was solved!

**Comment by ljudbane** [comment]
Hello.

I had the same problem building my project for ios. It turned out that i had to open project_name.xcworkspace file in Xcode, instead of project_name.xcodeproj as i was doing in the past. This way Xcode shows additional *Pods* project in project navigator.
