### ISSUE TITLE
Android Grouped Messages missing image since 2.1.x

### ISSUE THREAD

**Issue by Slind14** [OneSignal/OneSignal-Cordova-SDK#230]
Hi there,
I upgraded to 2.1.x, since then the grouped notifications (on android) do no longer display the image/icon.
I tracked it down to 2.1.0 being the first affected version, with 2.0.11 working properly.

Did I miss some API or setting changes?

**2.0.11**
![screen shot 2017-08-29 at 18 53 29](https://user-images.githubusercontent.com/3914677/29833349-69e2e468-8ceb-11e7-8d0b-cf02f400fd01.png)
**2.1.0 - 2.2.0**
![screen shot 2017-08-29 at 18 53 15](https://user-images.githubusercontent.com/3914677/29833350-6bc4b48c-8ceb-11e7-82fa-8b5c5c480380.png)

Disclaimer: The white circle would have been the icon, if I had set one, but that is not what I'm looking for.

**Comment by jkasten2** [comment]
@Slind14 The behavior you were seeing with the old SDK was an unintended one. The group summary was using the last notifications large icon before in versions 3.4.3 and older of the OneSignal SDK.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/37

If you want to use a large icon for all notifications including the group summary ones you can set a default one with the following instructions.
https://documentation.onesignal.com/docs/customize-notification-icons

**Comment by Slind14** [comment]
I have one icon per group (a group is a site). Is there any way to get this to work or would I need to stick with the old version?

**Comment by jkasten2** [comment]
@Slind14 There isn't a way to set a group summary icon (large or small). Just the default for all notifications.

Sorry for the unintended breaking change to your app. I'll mark this thread as feature request to be able to customize this in the future.

Note however the large icon for the summary / group notification in Android 7+ no longer displays. This is due to a large resign of notifications which allows for each sub notification to be fully expandable.

**Comment by Slind14** [comment]
Alright, thank you.
