### ISSUE TITLE
Not able to get Notification icon 

### ISSUE THREAD

**Issue by ankush1990** [OneSignal/OneSignal-Cordova-SDK#234]
This i have done but white bell icon is coming 

- <project-root>/platforms/android/res/drawable-mdpi/ (24x24)
- <project-root>/platforms/android/res/drawable-hdpi/ (36x36)
- <project-root>/platforms/android/res/drawable-xhdpi/ (48x48)
- <project-root>/platforms/android/res/drawable-xxhdpi/ (72x72)
- <project-root>/platforms/android/res/drawable-xxxhdpi/ (96x96)
- <project-root>/platforms/android/res/drawable-xxxhdpi/ (256x256) (Large Icon)

![screenshot_20170901-200148_20170901_200211231](https://user-images.githubusercontent.com/5012276/29974442-7b9ef5d6-8f50-11e7-9749-50d9572b35d3.jpg)

Please help

**Comment by Nightsd01** [comment]
We would recommend using the [Android Asset Studio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) if you have problems with icons.

In essence, you need to make sure the images are named `ic_stat_onesignal_default.png`

If you are still having problems, it likely is not caused by the OneSignal SDK.
