### ISSUE TITLE
Show pop up for notification out of app 

### ISSUE THREAD

**Issue by moh3n9595** [OneSignal/OneSignal-Cordova-SDK#238]
I use `onesignal-cordova-plugin` and it work very well, but I want show pop up like telegram app when notification received! example that what I want :
![sample](https://user-images.githubusercontent.com/20948388/30365727-de7b26ee-987d-11e7-8910-ea72ba786b4e.jpg)
How can I do this? Is anyway ?

**Comment by biborn** [comment]
This is called heads-up notification.
More info about that here: https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up

However, I haven't found a way to implement it in Ionic 3. Maybe someone will come up with a solution.

**Comment by jkasten2** [comment]
@moh3n9595 @biborn The buttons on the notifications are called [Action Buttons](https://documentation.onesignal.com/docs/action-buttons) on OneSignal.

To get the notification to be a head-up type which will show the expanded notification when it is received instead of having to view it in the shade set priority to 10. This is available on the [create notification REST API](https://documentation.onesignal.com/reference#section-delivery) as well as under Options>Android on the New Message page on the OneSignal dashboard.

**Comment by PaulPaulDevelops** [comment]
hey @jkasten2 

I'm currently using this in my Ionic 1 project. Push notifications are working as expected, except even with both of your recommendations (set priority to 10 when creating the notification, as well as manually push from the dashboard from this setting) I am unable to get the heads-up notification.
Any next steps I should take to debug this?

**Comment by fatsjohonimahnn** [comment]
The issue for this is heads up aka banner notifications only work on android 5 - 7.

For android 8+ they introduced Categories to make customizations to notifications and add this functionality there.

Please see our docs on Android Categories here: https://documentation.onesignal.com/docs/android-notification-categories

**Comment by PaulPaulDevelops** [comment]
@fatsjohonimahnn Awesome, thank you!

**Comment by jeeeanlefchak** [comment]
https://app.onesignal.com/apps
oneSingnal> settings> messages
-Add group
-Add categories
- Get the "channel ID"
- send message include post: android_channel_id = {channel ID}
