### ISSUE TITLE
window.plugins.OneSignal always 'undefined'

### ISSUE THREAD

**Issue by magaupee** [OneSignal/OneSignal-Cordova-SDK#266]
I'm getting window.plugins.OneSignal undefined in my ionicPlatform.ready function
I'm using cordova 6.3.1 and docs says minimum version is 6.4.0
My question is: My cordova version might be causing this problem?
Is there any way of using OneSignal with older versions of Cordova?
Unfortunately, due to compatibility issues with other plugins, I cannot update cordova for my project.
Any help will be appreciated.
Thanks.

**Comment by jkasten2** [comment]
@magaupee Version 6.4.0+ of Cordova is required since this is the first version that support Cocoapods that is used by this SDK. If you won't be building an iOS version of your app then you may use an older version of Cordova however we haven't tested this so you may run into other issues.

If you need iOS support and can't update to Cordova 6.4.0 you may use version 2.1.0 of the OneSignal SDK.

Note that you will also get an undefined error on `window.plugins` if you aren't running on a iOS or Android device as a web browser won't load the the OneSignal plugin.

**Comment by magaupee** [comment]
I managed to update my cordova version to 7.0.1 and successfully installed OneSignal plugin v2.2.2 But now I'm getting several errors in Genymotion Emulator, and Dashboard says device is not subscribed with error "**Outdated Google Play Services App**". What's wrong?

[https://imgur.com/a/es2w1](url)

**Comment by jkasten2** [comment]
@magaupee The emulator / device needs to have the "Google Play services" app on the device to register for FCM / GCM push notifications.  Since you are using the Genymotion emulator make sure to use Genymotion 2.10 or newer and follow their "Open GApp" widget guide:
https://www.genymotion.com/blog/2-10-open-gapps-widget/
