### ISSUE TITLE
Error when building on Phonegap Build

### ISSUE THREAD

**Issue by youradds** [OneSignal/OneSignal-Cordova-SDK#279]
I'm battling to get a new version out, and it seems like some stuff is broken. I have this in my config.xml:

`<preference name="phonegap-version" value="cli-6.5.0" />`

(it was cli-6.3.0)

...and then the plugin itself:

`<gap:plugin spec="https://github.com/OneSignal/OneSignal-Cordova-SDK.git" source="git" />	`

When I do the build, I get:

> Error - Plugin error (you probably need to remove plugin files from your app): //github.com/OneSignal/OneSignal-Cordova-SDK.git": Fetching plugin "https://github.com/OneSignal/OneSignal-Cordova-SDK.git" via git clone Using shallow clone Repository "https://github.com/OneSignal/OneSignal-Cordova-SDK.git" checked out to git ref "master" at "cf15856". Installing "onesignal-cordova-plugin" at "2.2.4" for ios Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1 at ChildProcess.whenDone (/private/tmp/gimlet/1180294/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23) at emitTwo (events.js:125:13) at ChildProcess.emit (events.js:213:7) at maybeClose (internal/child_process.js:897:16) at Socket.stream.socket.on (internal/child_process.js:340:11) at emitOne (events.js:115:13) at Socket.emit (events.js:210:7) at Pipe._handle.close [as _onclose] (net.js:549:12) pod: Command failed with exit code 1 - You can fix this here

What am I doing wrong? It all works on the old app (I'm having to re-make it, as the certificate is about to expire, and I wasn't expecting to have all this hassle :( )

Thanks

Andy

**Comment by jkasten2** [comment]
@youradds The latest version of the SDK requires cocoapods, you are building with PhoneGap CLI, please run the following to install it.
```bash
sudo gem install cocoapods
pod repo update
```
https://documentation.onesignal.com/docs/cordova-sdk-setup

If you are using PhoneGap build's cloud build I recommend trying to update to `cli-7.0.1`. Also if you have the following in your `config.xml` remove it as it could be overriding the platform version linked to the cli version.
```XML
<engine name="ios" spec="~4.0.0" />
```

Also note since you are point to the root of the OneSignal repo in `config.xml` your are building with the last commit. We recommend going though NPM instead since it will only update once we make a release.
```XML
<gap:plugin name="onesignal-cordova-plugin" spec="^2.1.1" source="npm" />
```

**Comment by youradds** [comment]
Thanks for the reply. I think it must have been an issue with the build server at Phonegap, as I tried it later on and it worked :)

**Comment by jkasten2** [comment]
@youradds Good to hear builds are working for your now! Feel free reply if you run into the same build error.
