### ISSUE TITLE
How to check if app is launched because of a notification open event

### ISSUE THREAD

**Issue by gnl1** [OneSignal/OneSignal-Cordova-SDK#302]
Hi,

I would like to know if there is a way to know if an app is launched because of a notification opened event. 

What I want to achieve is to prevent showing the app's root page and only show the notification handling page upon clicking on the notification if the application is not already running and is launched because of the user's tapping on the notification.

Thanks,
George

**Comment by Nightsd01** [comment]
@gnl1 When an app is launched because of a push notification, you can use the `handleNotificationOpened(callback)` function during OneSignal init to get alerted whenever a notification is opened.

I might suggest checking within the first 1 second of launch, or something to that effect. That would tell you that the app was opened from a push notification.

Here is an example of the init code we use in the example project, you can use the `handleNotificationOpened` callback like this:

```javascript
window.plugins.OneSignal
         .startInit("your_app_id")
         .handleNotificationReceived(function(jsonData) {
             // this just means the notification was received, not necessarily opened
         })
         .handleNotificationOpened(function(jsonData) {
             // A notification was opened
         })
         .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.InAppAlert)
         .iOSSettings(iosSettings)
         .endInit();
```

Please feel free to ask if you have any other questions or problems.
