### ISSUE TITLE
Cordova documentation error

### ISSUE THREAD

**Issue by giorgiobeggiora** [OneSignal/OneSignal-Cordova-SDK#335]
`startInit` requires googleProjectNumber as second parameter

	OneSignal.prototype.startInit = function(appId, googleProjectNumber) {
		OneSignal._appID = appId;
		OneSignal._googleProjectNumber = googleProjectNumber;
		return this;
	};

Without it, notifications on Android do not work, but the documentation does not specify it.

https://documentation.onesignal.com/v5.0/docs/cordova-sdk#section--startinit-

https://documentation.onesignal.com/docs/cordova-sdk-setup#section-2-add-required-code

Tested on an app that's using Google Cloud Messaging

**Comment by ecomunicarte** [comment]
It's optional since you might not want to send notifications to Android. But of course, if you want to send push notifications to Android devices, you need the ProjectNumber

**Comment by giorgiobeggiora** [comment]
i agree, but it's necessary to document it

**Comment by jkasten2** [comment]
@giorgiobeggiora The Google Project number / Sender ID on `startInit` was deprecated over a year ago which is why is removed from our docs. It will only be used if you created a OneSignal app before Oct. 2016 when we didn't require this to be added when setting up the Android platform on the dashboard. I updated the comment in our source to reflect this 5b2bf045a4dec9e573430b42411ac8c41c7d6316

**Comment by giorgiobeggiora** [comment]
Thank you. Anyway, who (like me) will make a new app starting from an old project he/she never worked on will not have an easy way to get this very important information.
