### ISSUE TITLE
can't receive notifications where another apps which also use the OneSignal are launched 

### ISSUE THREAD

**Issue by akudo7** [OneSignal/OneSignal-Cordova-SDK#336]
Hi all,

I am developing a few ionic iOS apps which use the OneSignal. Then if an app (A) only are launched, it can receive notifications. However it can't when another app (B) also is launched.
Have you ever hit and fixed this problem? They do not use same iOS bundle id, OneSIngnal App ID and REST API KEY offcourse.  

Thank you.
Akira

**Comment by Nightsd01** [comment]
I am closing this issue due to a lack of details. I will be happy to reopen once you provide some more information.

For example, what are app A and app B...? These are apps you are developing, both with Cordova? What version of the SDK are you using...? I don't know what you mean by 'launched', do you mean this happens when both apps are installed on the same device, or only when both apps are open at the same time?

**Comment by akudo7** [comment]
H Nightsd01,

Thanks for reply and advices.

All of my apps are built by a xcode project and they have a target of it and different bundle id.

A Xcode project
 + A target (bundle id for A and set One Signal for A in ionic)
 + B target (bundle id for B and set One Signal for B in ionic)
 + C target (bundle id for C and set One Signal for C in ionic)

Here is the system information.

node v6.11.1
npm 3.10.10

@ionic/cli-utils  : 1.19.0
ionic (Ionic CLI) : 3.19.0
global packages:

cordova (Cordova CLI) : 7.0.1
local packages:

@ionic/app-scripts : 3.0.1
Cordova Platforms  : android 6.3.0 ios 4.5.3
Ionic Framework    : ionic-angular 3.8.0
System:

Android SDK Tools : 26.0.2
ios-deploy        : 1.9.2
ios-sim           : 6.1.2
Node              : v6.11.1
npm               : 3.10.10
OS                : macOS High Sierra
Xcode             : Xcode 9.2 Build version 9C40b

**Comment by Nightsd01** [comment]
Hi @akudo7,

Can you post the Bundle ID’s for these two apps?

Because the push notifications do work when only one app is open, it’s likely not an issue with the SDK, it is likely an issue with certificates/etc.

**Comment by akudo7** [comment]
Hi Nightsd01

com.zerobillbank.zwallet.wolf
com.zerobillbank.zwallet.wolf.bene

Thanks
Akira

**Comment by Nightsd01** [comment]
@akudo7 Since apps are sandboxed (one app doesn't know about any other app), this would _not_ be an issue with the Cordova OneSignal SDK. 

In order to help you a bit further, we would want some more information specific to your app, this information should not be posted publicly, so I recommend contacting OneSignal support and I would be happy to help you on there. Just go to https://www.onesignal.com and click on the ***?*** button on the top right.
