### ISSUE TITLE
Plugin overwrites OTHER_CFLAGS

### ISSUE THREAD

**Issue by jurgen-reconcept** [OneSignal/OneSignal-Cordova-SDK#348]
I'm using this plugin with Ionic, which sets -DDEBUG on OTHER_CFLAGS. Apparently installing the onesignal plugin overwrites this, so that some of the debug functionality of Ionic does not work properly anymore.

I'm not an iOS native developer, so it took me a lot of time figuring out what the problem was, but now that I found it, I'm still not sure how to fix this.

**Comment by Nightsd01** [comment]
@jurgen-reconcept We've investigated this a bit more and can confirm that our SDK is _not_ setting/touching this flag. Since the Cordova SDK uses Cocoapods to install the OneSignal SDK, you can check your Pods project in the `.xcworkspace` project and make sure that none of the cocoa pod targets are setting this C flag.

**Comment by jurgen-reconcept** [comment]
Thanks for checking. I guess it is in fact the Cocoapods. But please understand that I don't have a clue what Cocoapods even are and how they relate to your SDK. So as an Ionic user it's strange that I try to install your SDK and it (indirectly) messes with Ionic.

For now I've resolved to manually setting it after I make a build. It's okay :)

**Comment by Nightsd01** [comment]
Cocoapods is basically like npm but for iOS dependencies. It can be a bit bug prone. Glad to hear you got it working!
