### ISSUE TITLE
window.plugins.OneSignal.getPermissionSubscriptionState returns different values on ios and android

### ISSUE THREAD

**Issue by lakshmana** [OneSignal/OneSignal-Cordova-SDK#359]
In contrast to what is documented on https://documentation.onesignal.com/docs/cordova-sdk#section--getpermissionsubscriptionstate- , the returned value 'status' on the callback function is different on ios and on android.
On ios device, the status will have the property status.permissionStatus.status with 0 = undetermined,
1 = Denied and 2 = Authorized

But on android, the status does not have the property permissionStatus.status. Instead android returns the status with permissionStatus.state as 1 = enabled and 2 = disabled 

Can you please check this on your side and if it is true then we need to normalize the return values or at least update the documentation. :)

Thx
Laxman

**Comment by Nightsd01** [comment]
@lakshmana This isn't exactly a bug, this is how it was intended. The status and state properties are different properties meaning different things, since the permission model in Android is different than it is in iOS (there is no 'unauthorized' state in Android for example). 

We have been considering making them more similar in the future but this would be a breaking change for one platform or another, so we will be doing it in the next major release.

**Comment by artuska** [comment]
> This isn't exactly a bug, this is how it was intended.
Well, this is a shitty intended coding.
