### ISSUE TITLE
userId is null in getPermissionSubscriptionState in subscriptionStatus

### ISSUE THREAD

**Issue by artuska** [OneSignal/OneSignal-Cordova-SDK#362]
This code:

```
window.plugins.OneSignal.getPermissionSubscriptionState((state: OnesignalSubscriptionState) => {
    console.log(state);
});
```

returns

```
export type OnesignalSubscriptionState = {
    subscriptionStatus: {
        userSubscriptionSetting: boolean;
        subscribed: boolean;
        userId: string;
        pushToken: string;
    };
    permissionStatus: {
        status: number;
        hasPrompted: boolean;
    };
}
```

with `userId: null`.

`onesignal-cordova-plugin: 2.3.3`

Everything works fine in version `2.2.5`.

**Comment by Nightsd01** [comment]
I am closing this issue due to a lack of details @artuska  but if you can add some more information I would be happy to reopen & investigate.

Is this an Android or iOS issue, or both...?

Does it occur on real devices or simulator, or both?

At some stages the userId is expected to be null. For example, when you just install the application and run it for the very first time, the userId will be null until the device is registered with OneSignal's API.
