### ISSUE TITLE
Handle notification before user's click

### ISSUE THREAD

**Issue by StefanoMartella** [OneSignal/OneSignal-Cordova-SDK#367]
is there any way to handle notification before user's click? I tried to use handleNotificationReceived function but it works only when the application is in foreground, when the application is in background or it is killed I receive the notification but the function is not fired. I need to get notification data even if the user swipe/delete it. 
Here's my code:

```
platform.ready().then(() => {
      .
      .
      .
      this.oneSignal.handleNotificationReceived().subscribe((data) => {
        console.log("Received");
      });
      .
      .
      .
    });
```

I'm on S6 android version 6.0.1

Thank you for the help

**Comment by Nightsd01** [comment]
Hi @StefanoMartella 

In order to do this, you would need to implement the Notification Service Extension (iOS) or the Notification Extender Service (android). Unfortunately you'd have to write native code (ObjC/Swift for iOS and Java/Kotlin for Android) as currently the SDK doesn't support running the Cordova runtime in the background. 

So in short, it's entirely possible, but you would need to implement the extension service. We have instructions for it here:
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-service-extensions (iOS)
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding (Android)
