### ISSUE TITLE
Using ActionButton in Ionic

### ISSUE THREAD

**Issue by JEricaM** [OneSignal/OneSignal-Cordova-SDK#368]
**Description:**

I'm developing an Ionic v3 application and I'm asking if is possible to use ActionButtons for example to let the user open a certain page of the app clicking the action button and so on...
If yes, how can I do it? I don't understand if and how is it possible checking the one signal or ionic documentation..

It's a supported feature or it's only native?

Thank you

**Comment by Nightsd01** [comment]
Hi, yes this is possible. When you initialize the SDK, you can use the `handleNotificationOpened` callback to process notification opens, including when users tap a button.

You can do it like this:

```javascript
var notificationOpenedCallback = function(jsonData) {
      // Check if the user tapped an action button and handle navigation
    };

    window["plugins"].OneSignal
      .startInit("YOUR_APPID", "YOUR_GOOGLE_PROJECT_NUMBER_IF_ANDROID")
      .handleNotificationOpened(notificationOpenedCallback)
      .endInit();
  });
```

In order to get the action buttons to show up, you need to add the Notification Service Extension, which our docs explain: https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-ios-part-2-recommend-

Please feel free to ask if you have any further questions and we'd be happy to help

**Comment by JEricaM** [comment]
thank you, but where is the documentation about how to interact with an action button, retrieving the action id, the text etc? I didn't find anything about this.
I've only found this https://documentation.onesignal.com/docs/customize-action-buttons but it doesn't help me :S
