### ISSUE TITLE
How to detect foreground or background mode with onesignal in cordova

### ISSUE THREAD

**Issue by jasonhai** [OneSignal/OneSignal-Cordova-SDK#401]
**Description:**

Hello team,

I integrated onesignal in our cordova app, but I dont see any option whether to check foreground or background mode in onesignal handleNotification function.

Is there any way to check it from cordova?

Best Regards!
      Jason

**Comment by Nightsd01** [comment]
Hi @jasonhai , 

On the `notificationOpened` handler, there will be a `result.notification.isAppInFocus` property. If the property is `true`, it means the app was open, otherwise, it means the app was in the background.

You can see details about our SDK by looking at our SDK reference:

https://documentation.onesignal.com/docs/cordova-sdk#section--osnotification-

Please feel free to reply if you have other questions and I'll be happy to reopen and help.

**Comment by jasonhai** [comment]
Thanks you so much @Nightsd01
