### ISSUE TITLE
OneSignal's Server URL change

### ISSUE THREAD

**Issue by appysaude** [OneSignal/OneSignal-Cordova-SDK#410]
**Description:**

Hi,

I am currently using OneSignal-Cordova-SDK in a Cross Platform Tool, where I develop my mobile apps for both iOS and Android. For architecture reasons, we need to set a proxy where all traffic coming and going to the mobile app will pass. 

Thus, we would like to configure on the SDK the proxy's URL, instead of having OneSignal's Server URL directly (of course that we will configure the proxy to forward the requests to OneSignal's server URL). We went through the SDK files but couldn't find the file where the URL is configured. Where can we change this URL? If this is not possible by changing the SDK, is there another way of making this change?

Thanks!

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
Hi @appysaude 

Our Cordova SDK is simply a wrapper on top of our native iOS and Android SDK's. These native SDK's have the server URL. 

In order to use a custom proxy URL, you would have to create custom builds of our native iOS and Android SDK's.

Since this is such a rare request, we don't have public instructions on how to build these native SDK's but it is not very complicated/obscure, they are a standard Objective-C iOS framework and an Android Java framework. 

You can find the repos here:

https://github.com/OneSignal/OneSignal-iOS-SDK
https://github.com/OneSignal/OneSignal-Android-SDK

Please feel free to ask if you have any other problems
