### ISSUE TITLE
Location does not updated continuously in iOS

### ISSUE THREAD

**Issue by bufpal** [OneSignal/OneSignal-Cordova-SDK#418]
**Description:**

Location point updated only once when I opened my app but location does not updated continuously even I move to other location in iOS.
Of course, I've granted the app location access(always).

However, android works fine with same code.

<pre>
<code>
      this.oneSignal.startInit(oneSignalAppId, sender_id);
      this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification);
      this.oneSignal.handleNotificationReceived().subscribe(data => console.log(data));
      this.oneSignal.handleNotificationOpened().subscribe(data => this.onPushOpened(data.notification.payload));
      this.oneSignal.endInit();
      
      this.oneSignal.promptLocation();
</code>
</pre>
**Environment**
1. What version of the Cordova SDK are you using?
 ionic - 4.1.1
 cordova - 8.0.0
 cordova - ios - 4.5.5

2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)
 cordova-plugin-device 2.0.2 "Device"
 cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
 cordova-plugin-ionic-webview 2.1.0 "cordova-plugin-ionic-webview"
 cordova-plugin-splashscreen 5.0.2 "Splashscreen"
 cordova-plugin-whitelist 1.3.3 "Whitelist"
 onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"

**Comment by Nightsd01** [comment]
@bufpal Sorry for the delay in getting back to you. If you are still encountering this problem, can you clarify what you mean?

When you say the location is not updated 'continuously' what do you mean? 

Keep in mind that our SDK will only send location every ~5 minutes when the app is open in the foreground, and at _min_ every 10 minutes in the background (depending on how your app is configured, it might not send background location at all).

Closing this issue because I am not sure it's actually an issue. If you think you are experiencing a bug (ie. location _never_ updates) please reply and I'll be happy to reopen and help investigate.
