### ISSUE TITLE
Admobpto incompatibility problem

### ISSUE THREAD

**Issue by Gercekefsane** [OneSignal/OneSignal-Cordova-SDK#444]
Hello I have the incompatibility issue with the Admobpro plugin. 2 Side cannot be installed at the same time. Can you solve the incompatibility problem?

**Comment by Nightsd01** [comment]
@Gercekefsane I am not sure what incompatibility issue you are talking about? Closing this issue due to lack of details...

If you are seeing some sort of error, please post that error and also post some details about what versions of each plugin you are using, etc.

Will reopen once you post more information.
