### ISSUE TITLE
Notifications from onesignal is triggering firebase FirebaseMessagingService 

### ISSUE THREAD

**Issue by nishkul** [OneSignal/OneSignal-Cordova-SDK#461]
**Description:**

I am getting two notification in some android device mostly in oppo device , While sending push notification from onesignal  is triggering or calling  firebase FirebaseMessagingService also .please me out how can resolve these issue 

**Environment**
Issue comming in Android as we have integrate both firebase  and onesigal pushnotiifcarion in single project 

Libaray version firebase and onesignal
  1.  classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
  2.  implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'
  3.  implementation 'com.google.firebase:firebase-messaging:17.3.4'
  4. implementation 'com.google.firebase:firebase-core:16.0.5'

**Comment by rgomezp** [comment]
Hello @nishkul 
Consider reviewing our [guide](https://documentation.onesignal.com/docs/idempotent-notification-requests) on mitigating duplicates for more info

**Comment by jemshit** [comment]
@rgomezp how that link is related to the question asked? Problem is not about sending duplicate notifications, it is receiving notification data in custom `FirebaseMessagingService` while Onesignal also handles the notification itself. Desired behavior is Onesignal's notifications should not trigger `FirebaseMessagingService` classes of other notification libraries

**Comment by jkasten2** [comment]
@nishkul @jemshit The native Android Java library `com.google.firebase:firebase-messaging` won't display a notification sent by OneSignal, since it checks the FCM payload format before processing it. A 2nd notification must being displayed from another library in the app.

@nishkul Can you run `cordova plugin list` to check for any other notification plugins? You can list them here and we can take a look too
