### ISSUE TITLE
No user in dashboard when init Onesignal after delete User via API

### ISSUE THREAD

**Issue by hellotoan1203** [OneSignal/OneSignal-Cordova-SDK#462]
**Description:**
Hi everyone, i'm using cordova-sdk in my android device( Samsung J7) and i have a problem. My case is:
 - When my app ready, i call setRequiresUserPrivacyConsent(true), call StartInit(), set call back function to handle push notification and endInit();
- When user clicks to button, I show a pop up, if user choose Allow, I call provideUserConsent(true) to complete initialization and I can see my device in OneSignal DashBoard.
 - I delete my device via using API delete.
 - If successfully, I call providerUserConsent(fasle) to prevent Onesignal automatically if I re-open my app.
 - After that, I call my function to re-initialize OneSignal again (startInit, set callback function and endinit).
- It works perfectly but when i go to OneSignal DashBoard I can't find my device to test notification.
This is my issue.
My code will be updated later. Because. I don't using my company's computer. 

**Environment**

1. I using Ionic 1, Cordova 7.1.0, Onesignal-Cordova-SDK:  2.4.3
2. 

**Steps to Reproduce Issue:**

1. Open App, 
2. Click Button **Subscribe**, a confirm pop up will be showed.
3. Choose Allow, Device Name has been seen in OneSignal User DashBoard (OUD)
4. Click to button delete user, It works perfectly and can't see this device Name in OUD
5. I click button subscribe again, but i can't see my device after refreshing OUD page.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay. Are you still facing this issue?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by jwitheford** [comment]
I am having a similar issue. I deleted a user from the onesignal dashboard and it won't appear when I restart my app. I am using ionic 3 and cordova, but calling `OneSignal.startInit()` doesn't add my device to the dashboard.

**Comment by rgomezp** [comment]
Thanks for your patience while we investigate

**Comment by jwitheford** [comment]
Thanks heaps, let me know if you need anything else

**Comment by jwitheford** [comment]
I managed to fix the issue I was experiencing by clearing the application data and restarting the app.
Previously I was uninstalling the app, and as it turns out Android doesn't clear app data on uninstall, because of its auto-backup feature. As noted [here](https://stackoverflow.com/questions/33169618/an-android-app-remembers-its-data-after-uninstall-and-reinstall/33176898) and [here](https://developer.android.com/guide/topics/data/autobackup).

I see that this is mentioned [here](https://documentation.onesignal.com/docs/users-and-devices#section-how-do-i-delete-several-unsubscribed-users-from-the-all-users-page-), 

So I guess the behaviour that I am seeing is intended, but it would be good if the SDK were able to handle it better and re-provision itself with the platform. Thanks for your help anyway.

**Comment by rgomezp** [comment]
My pleasure!
