### ISSUE TITLE
Turn off alert box

### ISSUE THREAD

**Issue by nicksrandall** [OneSignal/OneSignal-Cordova-SDK#51]
I want to turn off the alert box that shows up when a user gets a push notification while active in the app.
I have the following in my "deviceready" event handler: 

```js
window.plugins.OneSignal.enableInAppAlertNotification(false);
window.plugins.OneSignal.enableNotificationsWhenActive(false);
```
I have tried to do a clean build and it that has no effect.

**Comment by ahsan154** [comment]
hi experts, i had the same issue as above , i am getting this alert, and i don't this to appear but i dont know from where it is coming, i had same issue in both ios and android.... 

any help in this regard will be really appreciated...

let me share my javascript code as well that i got from your documentation

document.addEventListener('deviceready', function () {

    // Enable to debug issues.
    // window.plugins.OneSignal.setLogLevel({logLevel: 4, visualLevel: 4});
    myApp.showIndicator();
    var notificationOpenedCallback = function (jsonData) {
        //alert('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
        window.location = 'dashboard.html';
    };

    window.plugins.OneSignal.init("myonesingnalid",
            {googleProjectNumber: "my google project number"},
            notificationOpenedCallback);

    window.plugins.OneSignal.getIds(function (ids) {

        localStorage.setItem('player_id', ids.userId);
        myApp.hideIndicator();
      
    });

    // Show an alert box if a notification comes in when the user is in your app.
    window.plugins.OneSignal.enableInAppAlertNotification(false);
}, false);

![bug](https://cloud.githubusercontent.com/assets/12672971/15177492/c65fff88-1789-11e6-8eee-5dd31e9f2dcb.PNG)

**Comment by jkasten2** [comment]
The alert in your screenshot is from our example code. I see you have the alert commented out in the above code. Can you make sure your app got rebuilt correctly and you don't have another copy of this code somewhere else your app?

**Comment by jkasten2** [comment]
@nicksrandall @ahsan154 Were you able to resolve the issue by removing the example alert code?

**Comment by ahsan154** [comment]
yeah... i was not having any example alert code in the project, but what i did is: i placed cordova.js on the top of all the js files and then this onesignal code and then rest of the js files...
 

    On Friday, 20 May 2016, 4:09, Josh Kasten <notifications@github.com> wrote:
 

 @nicksrandall @ahsan154 Were you able to resolve the issue by removing the example alert code?—

**Comment by ricolo** [comment]
My issue is not exactly the same but similar. While I can turn off the in-app alert box using `enableInAppAlertNotification(false)`, the app would go to the screen specified by the push notification automatically upon the arrival of the notification (since `notificationOpenedCallback()` is fired, as stated in [documentation](https://documentation.onesignal.com/docs/phonegap--cordova-sdk-api#section-enablenotificationswhenactive)). This behavior is weird as the users suddenly lose control of the app and just get directed to whichever screen the push notification specifies.

While in Android, this seems to be overcome by the method `enableNotificationsWhenActive(true)` to suppress `notificationOpenedCallback()` from firing immediately, in iOS this would not work. @jkasten2 could this method `enableNotificationsWhenActive(true)` also be supported in iOS, or is there any work around on this issue?

I tested this with plugin version 1.12.4.

**Comment by jkasten2** [comment]
@ricolo We recommend keeping `enableInAppAlertNotification(true);` so notifications are not missed by the user when your app is in focus and for the redirect behavior you mentioned.

enableNotificationsWhenActive works since Android allows a ton of control over notifications. However on iOS when a push notification comes in while the app is in focus it skips displaying it and just fires the opened callback.

**Comment by matthieu80** [comment]
I have the same problem.
Every time a user receives a push notification and they are in the app, an alert is showed.
Here is my code:


    // PUSH NOTIFICATION BEGINS
    window.plugins.OneSignal
      .startInit("XXXX-XXXX-XXXX-XXX", "")
      .endInit();
    window.plugins.OneSignal.enableNotificationsWhenActive(false);
    window.plugins.OneSignal.getIds(function(response) {
      if (!$window.localStorage.getItem("signalId")) {
        $window.localStorage.setItem("signalId", response.userId)
      }
    });
    // PUSH NOTIFICATION ENDS

**Comment by jkasten2** [comment]
@matthieu80 `enableNotificationsWhenActive` has been removed in the 2.0.0 SDK. You must now use [`inFocusDisplaying`](https://documentation.onesignal.com/docs/cordova-sdk#section--infocusdisplaying-) instead.

**Comment by matthieu80** [comment]
@jkasten2
Thank you!
Nevertheless my problem is still there. I have no idea where these alerts come from.

**Comment by matthieu80** [comment]
@jkasten2
Thank you very much!

window.plugins.OneSignal
 .startInit("XXXX-XXXX-XXXX-XXX", "")
.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)  
.endInit();

**Comment by eugenemaning** [comment]
Depending on your preference, it's best to set it to
`window.plugins.OneSignal.OSInFocusDisplayOption.Notification`

If you use `.None` you will not receive the notification if your app is focused.
