### ISSUE TITLE
Rename package as cordova-plugin-onesignal

### ISSUE THREAD

**Issue by Aarbel** [OneSignal/OneSignal-Cordova-SDK#540]
To follow the Cordova guidelines, could be great to rename this plugin like the standards, ie `cordova-plugin-onesignal`

Cheers
![image](https://user-images.githubusercontent.com/25119847/63024998-9c71d600-bea8-11e9-976a-e9c746403fe9.png)

**Comment by jkasten2** [comment]
@Aarbel Thanks for the suggestion, I see all the Cordova plugins built by Cordova do start with `cordova-plugin-`, however I don't see this as a plugin naming convention recommendation in [Cordova's plugin documentation](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html). There only recommendation is as follows:
```
A npm-style identifier for the plugin.
```

Also I don't see a sizable benefit to changing the name, it would be a breaking change requiring everyone to update their `config.xml` to continue getting updates.

Due to these two considerations we have decided not do to this rename.

**Comment by Aarbel** [comment]
clear.
