### ISSUE TITLE
Not receiving silent notifications when app is in background/ kill/ swiped away

### ISSUE THREAD

**Issue by ravi-pandit14** [OneSignal/OneSignal-Cordova-SDK#561]
**Description**
We are facing an issue with “onesignal-cordova-plugin” in Ionic 3 app on an Android device.
When Ionic app is in background/kill then we are not able to fetch data if silent notification occurs.

**Some additional details about setup:**
We are also following the OneSignal docs for background notification https://documentation.onesignal.com/docs/service-extensions#section-notification-extender-service and it’s working when app is open and app is in foreground or running.

We have created this repository to replicate the issue easily. [Repository](https://github.com/ravi-pandit14/oneSignal-notification)

> Using package.json dependencies:

```
"onesignal-cordova-plugin": "2.6.0",
"cordova-android": "7.1.4",
"cordova-plugin-badge": "0.8.8",
"cordova-plugin-local-notification": "0.9.0-beta.2",
"ionic-angular": "3.9.5",
```

**Comment by anil-sookshum** [comment]
Me too facing the same problem.

**Comment by misog** [comment]
This occurs just in iOS 13 for me. Sometimes handleNotificationOpened handler is not called and sometimes it is called when app is closed (killed).

**Comment by ravi-pandit14** [comment]
@misog Have you tested this on Android as well? If so, are you able to receive notification and data on Android even if you kill app?

If notifications are working fine for you, it would be really helpful if you could provide a sample public repo.

**Comment by rgomezp** [comment]
@ravi-pandit14 , can you please take a look at our docs on Notification behavior? Perhaps you're seeing this due to one of the outline scenarios.

@misog , this is the expected behavior for silent notifications. That callback should only fire if the notification is tapped (not possible with silent notifs for obvious reasons)

@anil-sookshum , please provide some more info regarding your issue

**Comment by misog** [comment]
> @misog , this is the expected behavior for silent notifications. That callback should only fire if the notification is tapped (not possible with silent notifs for obvious reasons)

I think there was a misunderstanding. My problem is that this happens on iOS:
1. App is in killed state / in swiped away state (iOS).
2. Then notification is received and placed in iOS notification panel.
3. When I click on it then my cordova app is opened/loaded.
4. Then **sometimes** handleNotificationOpened handler is called and **sometimes** handleNotificationOpened is not called.

This is my issue - sometimes it works and sometimes it does not work and I do not know why, because the app starts from the same state (swiped away).

Is it possible to **always** run a handler in cordova sdk after user clicks on a notification, regardless of app state? The problem here are not notifications but the handler.

**Comment by rgomezp** [comment]
@misog 
this sounds like a different issue altogether than the title of this issue presents. please open its own issue

**Comment by rgomezp** [comment]
Closing due to no response
