### ISSUE TITLE
Background notifications when app is opened.

### ISSUE THREAD

**Issue by 2garryn** [OneSignal/OneSignal-Cordova-SDK#60]
In our application we need to have option to disable notifications. It means that user should not see real notifications in notification bar.
But at the same time we still need to get notifications in background when application is opened and in foreground to update our UI components according with additional data. So, user should not see notifications, but didReceiveRemoteNotificationCallBack should be executed for notifications when application is opened.
It works perfectly for iOS, when I create notification with flag content_available=1.
But it completely doesn't work for Android. 
I tried to use flag android_background_data=true and enabled verbose logging on phone. So I see some log message when notification is delivered to phone, but my callback still is not executed. 

Is it possible to implement described behaviour on current version of Cordova?

Thanks, 
Artem

**Comment by jkasten2** [comment]
@2garryn There isn't a simple way to do this for Android as a use case like this wasn't considered since push notifications are normally not used in this way.

It is possible with a `NotificationExtenderService` that is available in our SDK but it would require you to make your own Corodova plugin since it only works with native Java. See [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-and-notification-overriding) for details on the `NotificationExtenderService`.

Thanks.

**Comment by jkasten2** [comment]
@2garryn Feel free to reply and open this issue if you need any more information or run into any issues.
