### ISSUE TITLE
Support for background Data in android and ios for silent notifications

### ISSUE THREAD

**Issue by northkode** [OneSignal/OneSignal-Cordova-SDK#64]
Do we have to handle this with a custom receiver? or is there code in place to not show a notification but still pass the payload to the cordova app?

**Comment by JKalash** [comment]
Hi,

For iOS, there is no need to handle this using a custom receiver. a notification without a title / body, and setting content-available = 1 will trigger a silent notification in the background. U can use the OneSignalHandleNotificationBlock to handle the notification received.

**Comment by jkasten2** [comment]
@northkode For Android you can use the `NotificationExtenderService` noted in our [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-and-notification-overriding).

Feel free to reopen this issue if you have additional questions on this.

**Comment by epetre** [comment]
So there is no way to do it directly with this plugin for both devices without changing the native code?

**Comment by jkasten2** [comment]
@epetre Correct for apps out of focus. It wouldn't be recommend to start the whole Cordova runtime to process as this puts extra battery and memory pressure on the device vs native only code.

**Comment by epetre** [comment]
do you guys have any example on how we could achieve this for ios and android or what parts of this plugin are the best suited to insert an interception of a notification or some filtering based on the notification data?

I think this is the doc for [android](https://documentation.onesignal.com/docs/android-customizations#background-data-and-notification-overriding). But it could be nice to have some pointers on what to override in this cordova plugin to filter or do some processing work based on the pushes we get.

**Comment by jkasten2** [comment]
@epetre For Android you can either fork the plugin or create your own. There is a guide the I skimmed over that covers creating a Cordova plugin well.
https://gist.github.com/mlynch/c9a469948680979a8740d68c47d1cf98
It would be more work to create your own plugin instead of forking this one but it would be easier to update to newer version of this plugin this way.

Basically the Android OneSignal guide you can be adapted to Cordova by creating own new `.java` class file. Then add it to `plugin.xml` next the other .java file.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/plugin.xml#L63

Add the `AndroidManifest.xml` setting to this part of the `plugin.xml`.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/plugin.xml#L49



iOS is more coupled so this is much more difficult to create you own plugin. You may want just fork this to get it implemented much quicker. The native retrieved handled can be added here.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/src/ios/OneSignalPush.m#L88

The option received block is noted here.
https://documentation.onesignal.com/docs/ios-native-sdk#section--initwithlaunchoptions-

**Comment by floydus** [comment]
I was able to implement the NotificationExtenderService successfully but my issue is that I need the NotificationReceivedHandler from ionic to be called anyway(I'm doing some calls depending on the additionalData passed).
Instead of calling displayNotification(overrideSettings) to trigger my handler, is there a way not to show the alert and still call the super handler (ionic side).
I have created a question on this see -> [https://stackoverflow.com/questions/46392556/notificationextenderservice-not-firing-handlenotificationreceived](url).
Thanks

**Comment by ciekawy** [comment]
what @floydus mentioning is pretty common case I believe. I.e showing the notification when the app is not in foreground and handle incoming data without showing notification when in foreground.

Wonder if there is a chance for this to be addressed in any of existing forks.
