### ISSUE TITLE
Webhooks for delivered notifications.

### ISSUE THREAD

**Issue by tenbits** [OneSignal/OneSignal-Cordova-SDK#685]
Dear OneSignal Cordova Team, 

would it be possible to implement the webhooks when the push is delivered. Same as the `Web SDK` does - https://documentation.onesignal.com/docs/webhooks 

Or is there any similar functionality, so we can notify the server to know, that the push is delivered, even when the app is closed? 

Thank you in advance.

**Comment by rgomezp** [comment]
@tenbits ,
Thanks for your patience.

We have actually built this functionality as a feature. Please take a look at our [Confirmed Deliveries reference](https://documentation.onesignal.com/docs/confirmed-deliveries).

Please note that this _is_ a paid feature.

Hope this helps.

Enjoy!

**Comment by tenbits** [comment]
@rgomezp, Thank you for the reply. 

Yes, the Confirmed Deliveries are actually what is desired, but it misses further forwarding to our server. In other words, as soon as the delivery is confirmed by the SDK, OneSignal has no way to notify by a webhook our server. As a workaround for us would be to poll the onesignal API (https://documentation.onesignal.com/reference/view-notification) by the notification ID to continuously update the `received` property.  _But this is quit ugly hack_ Would you have any suggestions in this case? Thanks

**Comment by rgomezp** [comment]
@tenbits ,
Good question.

Currently we do not support this functionality though it _is_ something we are expecting to build in the future. As a workaround, you can consider using the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) to make the request yourself in the [background](https://documentation.onesignal.com/docs/data-notifications) to your servers.

Be prepared to write some native code since this is a non-native SDK, however.

**Comment by tenbits** [comment]
Thank you Rodrigo, 

Service Extensions were also the options, I just hoped it could be some easier way, as the SDK already handles delivery confirmations, so that it could be possible to call the webhook upon delivery by the SDK on the device, or even the OneSignal backend could fire-and-forget the webhook to our server by receiving the confirmation from the device.

Anyway, thank you for your help, stay healthy!
