### ISSUE TITLE
Java RUNTIME version compile

### ISSUE THREAD

**Issue by jadayash** [OneSignal/OneSignal-Cordova-SDK#708]
After trying to build my application

am getting this error, I removed onesignal-cordova-plugin , the app succeeds in built.

```
1: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\Jad\Desktop\Ionic\appname\platforms\android\onesignal-cordova-plugin\appname-build-extras-onesignal.gradle' line: 24

* What went wrong:
A problem occurred evaluating script.
> com/onesignal/androidsdk/GradleProjectPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Run
time only recognizes class file versions up to 52.0
```

**Comment by jkasten2** [comment]
Thanks for reporting! Java 8 compatibility has been fully restored in the [onesignal-gradle-plugin 0.13.4](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4) Release.

Re-sync gradle in Android Studio and /or performing a clean build should result in automatically upgrading.

**Comment by jadayash** [comment]
Thnaks for the quick update.

I performed a clean build but still getting same issue

**Comment by jadayash** [comment]
![Capture](https://user-images.githubusercontent.com/66420205/121752884-d5694900-cb19-11eb-8f6c-d98c70496260.PNG)

stil 0.13.4 isn't available in gradle

**Comment by jkasten2** [comment]
I can confirm the latest 0.13.4 version is available as noted here:
https://plugins.gradle.org/plugin/com.onesignal.androidsdk.onesignal-gradle-plugin

The issue is most likely a version caching issue. It depends on your configuration but I could take up to 24 hours for your system to decided to check for a new version. To refresh the cache however there are a few options.
### Option 1 - One time refresh
From you project directory where your `build.gradle` file is located run:
Windows:
```
gradlew.bat --refresh-dependencies
```
Linux / Mac:
```
./gradlew --refresh-dependencies
```

### Option 2 - Change cacheDynamicVersionsFor
In your root `build.gradle` add the following section.
```
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
}
```
Gradle reference: https://discuss.gradle.org/t/refresh-dependencies-should-use-cachechangingmodulesfor-0s/556/7

**Comment by jadayash** [comment]
Thank you, working great now
