### ISSUE TITLE
User created without device token on iOS

### ISSUE THREAD

**Issue by yingliangzhang** [OneSignal/OneSignal-Cordova-SDK#71]
Hi,

I'm using the ionic SDK for both Android and iOS for a locally hosted Parse app. I installed the plugin and called the `init` function like below during bootstrap:

```
window.plugins.OneSignal.init("b2f7f966-d8cc-11e4-bed1-df8f05be55ba",
                                 {googleProjectNumber: "703322744261"},
                                 notificationOpenedCallback);
```

I have the `googleProjectNumber` filled in but I guess this should also work for iOS. On login , users are created in OneSignal and it works fine for Android. However, for iOS, the user doesn't have the device token set.

![snip20160822_21](https://cloud.githubusercontent.com/assets/3793091/17845367/b0ea7b1e-6884-11e6-8424-72d7773b02e6.png)

Has anyone experienced same issue before? Any help is much appreciated.

**Comment by jkasten2** [comment]
@yingliangzhang Make sure you setup your provisioning profile correctly and it is synced to your system through Xcode. See our [5. Provisioning Profiles](https://documentation.onesignal.com/docs/generating-an-ios-push-certificate#5-provisioning-profiles) instructions.

Also make sure you don't have any other push notifications plugins in your app like Ionic push that can interfere with OneSignal getting a push token.

Thanks.

**Comment by abihari** [comment]
@jkasten2 I am seeing the same issue as the original poster on iOS. Things were working fine before, but I had to switch computers and ended up getting a mismatch issue with certificates.

Additionally, I also upgraded to XCode 8.0 and iOS 10.0.1 on my iPhone.

After re-generating all of the certificates and provisioning profiles, I've uploaded the right things to OneSignal and no longer get the mismatch error. However, my iPhone continues to initialize the Ionic/Cordova SDK and not get a push token.

My provisioning profiles have Push Notification enabled and I've enabled Push Notification entitlements in XCode.

Any ideas on what to do/check next?

Regards

**Comment by itemir** [comment]
I am having the same problem. push_token is coming up as empty OneSignal.getIds. This was working before. I have upgraded to XCode 8.0 and iOS 10 in the meantime. No additional plugins have been added since. 

P.S. The link given above (https://documentation.onesignal.com/docs/generating-an-ios-push-certificate#5-provisioning-profiles) is giving an HTTP-404.

**Comment by rwasef1830** [comment]
Additional steps needed on xcode 8 / ios 10:

http://support.iterable.com/hc/en-us/articles/212157066-iOS-10-Debugging-Push-Notifications-Not-Registering

In addition to previous guidance on provisioning profile. The onesignal cordova SDK needs to be updated to modify the platform xcode project to do these steps automatically when the plugin is installed. Otherwise, these steps must be redone everytime ios platform is removed/readded (or doing ```ionic state reset``` for example).

**Comment by itemir** [comment]
Thanks @rwasef1830, this solved the issue for me.

**Comment by jkasten2** [comment]
We have now have this in our setup instructions as well.
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios

Thanks.
