### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by sombriks** [OneSignal/OneSignal-Cordova-SDK#80]
Hello all,

i`m facing this issue:

> In file included from /Users/sombriks/git/roundabout/roundaboutapp/platforms/ios/Ambbi/Plugins/onesignal-cordova-plugin/OneSignalTrackIAP.m:31:
> /Users/sombriks/git/roundabout/roundaboutapp/platforms/ios/Ambbi/Plugins/onesignal-cordova-plugin/OneSignal.h:166:25: error: expected a type
> + (void) onesignal_Log:(ONE_S_LOG_LEVEL)logLevel message:(NSString*)message;

my cordova version is 6.3.1

onesignal plugin is:

> onesignal-cordova-plugin 2.0.2 "OneSignal Push Notifications"

Any guidance is welcome

**Comment by sombriks** [comment]
on a second project, build goes fine, same cordova, but the plugin version is quite outdated:

> onesignal-cordova-plugin 1.13.1 "OneSignal Push Notifications"

**Comment by sombriks** [comment]
i can confirm that downgrade to 1.13.2 fixed the build issue.

if i can ask, upgrade to 2.x series will force me to rewrite my code on device? 

https://documentation.onesignal.com/docs/cordova-sdk

the new API looks much more decent, yet i prefer to prepare myself tor it on another time.

**Comment by seme1** [comment]
Is there a guide for how to upgrade a cordova app to the 2.x version of the OneSignal SDK ?

**Comment by sombriks** [comment]
@seme1 the best i could find was the new docs but no clue where the old documentation lies now.

**Comment by JKalash** [comment]
Hi there,

Thank you for contacting OneSignal. We are working on updating our recently released 2.0 version of the SDK to squash some bugs. As to your question, our 2.0 SDK is not backwards compatible with the 1.+ as it adds support to our more recent versions of the native iOS and Android SDK which, in turn, are not backwards compatible since the major version update.

For a native upgrade you should have a look at: [iOS upgrade guide](https://documentation.onesignal.com/docs/upgrading-to-ios-sdk-20) / [Android upgrade guide](https://documentation.onesignal.com/docs/upgrading-to-android-sdk-30) for a better understanding of the changes that took place.

**Comment by jkasten2** [comment]
@seme1 @sombriks We have released our 2.0 SDK and our setup instructions can be found below.
https://documentation.onesignal.com/docs/cordova-sdk-setup

You may need to remove and re-add our plugin to get it updated.

Thanks.

**Comment by sombriks** [comment]
very nice @jkasten2 , thank you so much!

on my next app update i'll upgrade the plugin.
