### ISSUE TITLE
OneSignal.setNotificationWillShowInForegroundHandler() is not calling

### ISSUE THREAD

**Issue by desog11** [OneSignal/OneSignal-Cordova-SDK#812]
**Description:**

I am receiving notification from the API (https://onesignal.com/api/v1/notifications) using postman. I can see in Logs but below handler method never get called

**Environment**

Ionic CLI                     : 6.17.1
Ionic Framework               : @ionic/angular 5.9.4
@angular-devkit/build-angular : 12.1.4
@angular-devkit/schematics     : 12.1.4
@angular/cli                             : 12.1.4
@ionic/angular-toolkit              : 4.0.0
Android SDK Tools : 26.1.1

onesignal-cordova-plugin 3.1.1 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. I have the next code: 
```  
init() {
        OneSignal.setLogLevel(5, 0);
        OneSignal.setAppId(APPID)
        console.log("OneSignal Object:", OneSignal);
          OneSignal.setNotificationWillShowInForegroundHandler((notificationReceivedEvent) => {
          console.log('FOREGROUND HANDLER CALLED WITH:', notificationReceivedEvent)
          const notification = notificationReceivedEvent.getNotification();
          alert(notification.body);
          console.log(notification.body)
          notificationReceivedEvent.complete(notification);
      });
}
```
But the app never display the text on console.log inside setNotificationWillShowInForegroundHandler
2. I can see notification in logs
``` 
"custom":"{\"a\":{\"data\":\"{\\\"transaction\\\":\\\"01\\\", \\\"value\\\":\\\"1\\\",\\\"ok\\\":\\\"1\\\"}\"}
``` 

**Anything else:**
I'm using Android 12.
Please guide what's wrong here ?

**Comment by gugahoi** [comment]
If you are using Capacitor then I think the problem stems from Capacitor's default push notification behavior and it taking precedence over the OneSignal handler. I've noted a potential solution to have notifications show in the foreground [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/733#issuecomment-1228020071).

**Comment by emawby** [comment]
@desog11 Is the previous answer sufficient for your needs?

**Comment by desog11** [comment]
Thank you for reply @gugahoi, but not i use only cordova to use onesignal in the project.
I can see in the logs that it is receiving the notification but I can't get the 'setNotificationWillShowInForegroundHandler' method to fire.

**Comment by lbarriosbdg** [comment]
I am having the same issue :(

**Comment by jennantilla** [comment]
Hello everyone! Apologies that this issue has gone stale. Since it has been some time since any activity here, I'm going to close this out. 

If this is still a concern for anyone, please @ mention me and we can resume discussion.

We have a new major release update that includes many enhancements and improvements, including a new method for handling foreground notifications. I encourage everyone to update to the [latest SDK version](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.1.2). Please see the [migration guide](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/main/MIGRATION_GUIDE.md) for more details.

Thanks!

**Comment by lamlengend98** [comment]
@jennantilla still got this problem
