### ISSUE TITLE
[Bug]: Android 12 targetSdkVersion 31   cannot receive notification

### ISSUE THREAD

**Issue by peixin** [OneSignal/OneSignal-Cordova-SDK#826]
### What happened?

Hi, because upload to Google Play requires upgrade targetSdkVersion to 31. and set exported has been done and can be installed in Android 12, but testing found that we can't receive the notification and there is no error message.

I am now using onesignal-cordova-plugin:2.11.3(com.onesignal:OneSignal:3.15.7) capacitor 2,  and I can't upgrade the plugin for now.

How can I solve this problem?

### Steps to reproduce?

```Markdown
1. launch app
2. push message use OneSignal Dashboard by tag
```

### What did you expect to happen?

can receive notification

### OneSignal Cordova SDK version

com.onesignal:OneSignal:3.15.7

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slyd4r** [comment]
here I will give you different solutions until they update the plugin and the docs :
**method one :** ignore importing the plugin , and use this **window['plugins'].OneSignal** instead of **this.oneSignal**
make sure to use the right method because there are some changes which are not yet updated in the docs , but you can find them here https://documentation.onesignal.com/docs/cordova-sdk-setup
for example : old method -> this.oneSignal.startInit(app_key, sender_id);
                     new method ->window['plugins'].OneSignal.setAppId(app_key);

**method two** you can still use the old plugin (version 2.**)  but you have to update it your self so that it fits android api 31 version , and they said that any element(activity , service or receiver) that contains  intent filter should have [android:exported] value , follow this  link to understand (https://developer.android.com/guide/topics/manifest/activity-element#exported)

I hope it helps .

**Comment by mkwitko** [comment]
> here I will give you different solutions until they update the plugin and the docs : **method one :** ignore importing the plugin , and use this **window['plugins'].OneSignal** instead of **this.oneSignal** make sure to use the right method because there are some changes which are not yet updated in the docs , but you can find them here https://documentation.onesignal.com/docs/cordova-sdk-setup for example : old method -> this.oneSignal.startInit(app_key, sender_id); new method ->window['plugins'].OneSignal.setAppId(app_key);
> 
> **method two** you can still use the old plugin (version 2.**) but you have to update it your self so that it fits android api 31 version , and they said that any element(activity , service or receiver) that contains intent filter should have [android:exported] value , follow this link to understand (https://developer.android.com/guide/topics/manifest/activity-element#exported)
> 
> I hope it helps .

didnt work for me :/

**Comment by slyd4r** [comment]
> 
make sure that you are using **onesignal-cordova-plugin V3^**  , you can find it on packge.json file .
you check if the plugin is running on your device by triggering an action .. for exmaple:
window['plugins'].OneSignal.getDeviceState((state:any)=>{
    console.log("state : " +state);
  })

**Comment by peixin** [comment]
upgrade to "onesignal-cordova-plugin": "3.0.4" resolved. 

why not use latest 3.3.0 because  3.3.0 need Android target SDK version to 33+.
