### ISSUE TITLE
Ionic release target failing because of lint errors caused by Onesignal SDK.

### ISSUE THREAD

**Issue by srikanth235** [OneSignal/OneSignal-Cordova-SDK#84]
This is not a serious issue and can be bypassed by changing build.gradle file. Fixing it would be nice though. The following are the error details: 

>  Error: The <uses-permission> element must be a direct child of the <manifest> root element [WrongManifestParent]
>         <uses-permission android:name="com.amazon.device.messaging.permission.RECEIVE" />
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>    Explanation for issues of type "WrongManifestParent":
>    The <uses-library> element should be defined as a direct child of the
>    <application> tag, not the <manifest> tag or an <activity> tag. Similarly,
>    a <uses-sdk> tag much be declared at the root level, and so on. This check
>    looks for incorrect declaration locations in the manifest, and complains if
>    an element is found in the wrong place.
> 
>    http://developer.android.com/guide/topics/manifest/manifest-intro.html
> 
> 1 errors, 0 warnings
>

**Comment by msbit** [comment]
@jkasten2 applying https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/cb852cd0f4092931ee5e92d3e36c0d647964736c to https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/47e84184258d58da039dc1b7a4ef20dd53998106 should fix this error in the 1.13.x release.

**Comment by jkasten2** [comment]
@srikanth235 We don't have any plans to update the 1.X version of our SDK since 2.0 is release. Please update to our 2.0.4 SDK to get this fix.

You may need to remove and re-ad our SDK to get the update.

See our instructions before to setup the new SDK.
https://documentation.onesignal.com/docs/cordova-sdk-setup

Thanks.

**Comment by msbit** [comment]
@jkasten2 I can understand you'd prefer to not maintain 1.x and focus on 2.x, but this issue was pushed up as part of https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/fcd37d1c167597ba7da526de65eceb4576893374, chronologically and historically before the release of 2.0.1 (https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/a93ba0f5fb1fccf7fbfbdd75c182ab5866452e9f).

I feel like this one issue, which was only added recently and _should_ just be a backport of an existing commit, would warrant some support on a 1.x branch.
