### ISSUE TITLE
window.plugins.OneSignal.Notifications.canRequestPermission not returning anything.

### ISSUE THREAD

**Issue by RZR666** [OneSignal/OneSignal-Cordova-SDK#949]
### How can we help?

Ok, 

Fresh app, accept soft prompt IAP permission, all good.

Disable push permissions in android setting.

Enter app again, and soft prompt wont appear.  So I try canRequestPermission and it doesn't return anything.

How can I handle a situation like this?

Many Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello there--apologies for missing this issue. We have made many improvements to our SDK since this was reported that could resolve this issue. Please update to our [latest version](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.2.8) and if you still have any problems, feel free to create a new issue. Thanks!
