### ISSUE TITLE
[question]: Which updates will we have to do because of the FCM deprecation

### ISSUE THREAD

**Issue by Marceldts** [OneSignal/OneSignal-Cordova-SDK#965]
### How can we help?

We have an Ionic/Cordova app that uses "onesignal-cordova-plugin@2.11.4" (if it helps, we are using it with ionic-native/onesignal). Which changes will we have to make due to [FCM's legacy protocols depreaction](https://firebase.google.com/support/faq?hl=es#fcm-23-deprecation)?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @Marceldts apologies for the delay in getting back to you. 

We’ve worked hard to handle the heavy lifting of the FCM migration so that our existing users are able to get up to speed in a couple of simple, quick steps. To make sure you're set up for success when the depreciation occurs, follow [Step 2: Ensure Firebase Cloud Messaging API (V1) is Enabled](https://documentation.onesignal.com/docs/generate-firebase-credentials#2-ensure-firebase-cloud-messaging-api-v1-is-enabled) in our Android: Firebase Credentials documentation. Questions? Check out our [FCM Deprecation FAQs.](https://documentation.onesignal.com/docs/generate-firebase-credentials#faq)

You can read more about it [here](https://onesignal.com/blog/what-you-should-know-about-the-fcm-deprecation-announcement/).

I'd also recommend upgrading to our latest major release, [5.1.2](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.1.2). Please see our [migration guide](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/main/MIGRATION_GUIDE.md) for more details.
