### ISSUE TITLE
[question]: Prevent InAppMessage from opening external browser

### ISSUE THREAD

**Issue by felicienfrancois** [OneSignal/OneSignal-Cordova-SDK#985]
### How can we help?

I would like to intercept InAppMessage clicks and open data.result.url inside the app if the url match a pattern.
I've tried the following:

         plugins.OneSignal.InAppMessages.addEventListener("click", (data) => {
            if (data.result.url && pattern.test(data.result.url)) {
              openInApp(data.result.url);
              // prevent from opening in browser
              return false;
            }
          });

But looking at the code, it seems there is no way to prevent default, like in Notifications handlers.
Is there any way to prevent opening in external browser ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @felicienfrancois instead of opening a default browser, are you wishing to deep link to another page of your app? If so, [this documentation](https://documentation.onesignal.com/docs/iam-click-actions#how-to-deep-link-within-the-app) may help. Feel free to share a bit more about your use case if this doesn't fulfill your needs!

**Comment by jennantilla** [comment]
Closing due to no response. Please feel free to comment if you are still having issues!
