### ISSUE TITLE
[question]: Capacitor 6 support?

### ISSUE THREAD

**Issue by fmp777** [OneSignal/OneSignal-Cordova-SDK#995]
### How can we help?

Has this been updated to support Capacitor 6?
`[!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webbpage** [comment]
@fmp777 OneSignalXCFramework updates are separate from your npm plugin updates. This is my least favorite Capacitor plugin to update since it's rare I do not run into issues.

Try this to update your OneSignalXCFramework: 
<img width="346" alt="Screenshot 2024-05-29 at 7 40 23 AM" src="https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/523477/c8930512-e53c-4279-97e7-568909b8b933">

Your PodFile and PackageDependencies Rules could also limit your max version for OneSignalXCFramework so be mindful of that configuration.

Please report back if you have OneSignal working with Capacitor 6.0. I'll need to make this upgrade soon as well.

**Comment by jennantilla** [comment]
Hello @fmp777  and @webbpage. Just wanted to chime in here that this plugin works with Capacitor 6.

In our latest release, we included an [example Ionic Capacitor example app](https://github.com/OneSignal/OneSignal-Cordova-SDK/tree/main/example/IonicCapOneSignal) that also uses Capacitor 6, so feel free to check that out!

You can also try running `pod install --repo-update` from your app's `ios` directory if you are having trouble updating cocoapods.

If you are still having issues, updating, let me know and I'll be happy to assist!
